[package]
name = "memory_allocator"
version = "0.1.0"
authors = ["own"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use_spin"]
use_spin = ["spin"]

[dependencies.spin]
version = "0.5"
optional = true